### ISSUE TITLE
Directly opening observation yields an error

### ISSUE THREAD

**Issue by jamessynge** [panoptes/panoptes-network#4]
For example: http://www.panoptes-data.net/observations/PAN006_6575fc_20181019T225012
This currently prints "Error".

**Comment by wtgee** [comment]
This is due to the Vue router. It is "fixed" by just setting the normal error (404) page to redirect to index.html, which will in turn cause the page to load.

However some other errors are introduced which I'm not solving this exact second: #14, #15

https://cloud.google.com/storage/docs/hosting-static-website
